# Generated by Django 5.2.7 on 2025-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.IntegerField(
                default=0, help_text="0 = first login, 1 = profile updated"
            ),
        ),
    ]
